version: 2
build:
  image: latest
python:
  version: '3.8'
  install:
    - requirements: dev/requirements.txt
    - method: pip
      path: .
    - requirements: docs/fallback_theme.txt
  system_packages: true
formats: all
